include $(GOROOT)/src/Make.inc
TARG= 	waffle
GOFILES= 	master.go msg.go msgq.go node.go partition.go vertex.go edge.go loader.go worker.go vertq.go combiner.go aggregator.go result.go persist.go waffle.go

include $(GOROOT)/src/Make.pkg
