include $(GOROOT)/src/Make.inc
TARG= 	waffle
GOFILES= 	master.go \
			rpc.go \
			msg.go \
			node.go \
			partition.go \
			vertex.go \
			edge.go \
			loader.go \
			worker.go \
			combiner.go \
			aggregator.go \
			result.go \
			persist.go \
			waffle.go \
			tasks.go \
			util/gob_persist.go

include $(GOROOT)/src/Make.pkg
